add Tmux with instructions
koesterlab/data-science-for-bioinfo pull request #16
Opened 2023-06-19 13:02 UTC by huzuner

2023-06-19 16:47 UTC, dlaehnemann requested changes
Some small suggestions for the wording and formatting.

Other than that, the new page needs a reference to it in [`SUMMARY.md`](https://github.com/koesterlab/data-science-for-bioinfo/blob/tmux/src/SUMMARY.md?plain=1), but after that, it's good to go.

2023-06-20 08:11 UTC, huzuner commented
Done, thank you!

2023-06-20 08:55 UTC, dlaehnemann approved these changes

2023-06-20 08:55 UTC, dlaehnemann commented
Thanks for this great addition!

2023-06-20 08:55 UTC, merged